name: Professional CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  java-build-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build & Test Java
        run: mvn clean verify

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=HamzaAfif_Basic_cicd \
            -Dsonar.organization=hamzaafif \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Java Docker Image
        run: docker build -t java-service .


  node-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './nodejs-app/package-lock.json'

      - name: Node.js Test
        run: |
          cd nodejs-app
          npm ci
          npx jest

      - name: Build Node Docker Image
        run: docker build -t nodejs-service -f nodejs-app/Dockerfile ./nodejs-app

  # --- JOB 3: PYTHON (Runs in parallel) ---
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Python Test
        run: |
          cd python-app
          pip install -r requirement.txt pytest
          pytest

      - name: Build Python Docker Image
        run: docker build -t python-service -f python-app/Dockerfile ./python-app


  delivery:
    needs: [java-build-analysis, node-test, python-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: CI Success Message
        run: |
          echo "âœ… All Quality Gates Passed"
          echo "ðŸš€ Ready for Deployment"