name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './nodejs-app/package-lock.json'

      - name: Build & Test Java
        run: mvn clean verify

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=HamzaAfif_Basic_cicd \
            -Dsonar.organization=hamzaafif \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Java Docker Image
        run: docker build -t java-service .

      - name: Node.js Test
        run: |
          cd nodejs-app
          npm ci
          chmod +x ./node_modules/.bin/jest
          npm test

      - name: Build Node Docker Image
        run: docker build -t nodejs-service -f nodejs-app/Dockerfile ./nodejs-app


      - name: Python Test
        run: |
          cd python-app
          pip install -r requirement.txt pytest
          pytest

      - name: Build Python Docker Image
        run: docker build -t python-service -f python-app/Dockerfile ./python-app

      - name: CI Success Message
        run: |
          echo "✅ SonarCloud passed"
          echo "✅ Java, Node, + Python builds OK"
          echo "✅ All Docker images created"